# Generated by Django 5.0 on 2023-12-18 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos_Clientes',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome_grupo', models.CharField(max_length=255, verbose_name='Nome Grupo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Grupos Clientes',
            },
        ),
        migrations.CreateModel(
            name='Cadastro_Pessoal',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=255, null=True, verbose_name='Nome ou Razão Social')),
                ('cpf_cnpj', models.CharField(max_length=30, null=True, verbose_name='CPF ou CNPJ')),
                ('data_nascimento', models.DateField(null=True, verbose_name='Data Nascimento')),
                ('contato1', models.CharField(max_length=100, null=True, verbose_name='Contato 01')),
                ('profissao', models.CharField(max_length=255, null=True, verbose_name='Profissão')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.grupos_clientes', verbose_name='Id do Grupo')),
            ],
            options={
                'verbose_name_plural': 'Cadastro Pessoal',
            },
        ),
    ]
