# Generated by Django 5.0 on 2024-01-05 11:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Nome Fase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fases',
            },
        ),
        migrations.RemoveField(
            model_name='pipe_produtos',
            name='phase_id',
        ),
        migrations.RemoveField(
            model_name='pipe_produtos',
            name='phase_name',
        ),
        migrations.AddField(
            model_name='pipe_produtos',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fase', verbose_name='Fase'),
        ),
    ]
