# Generated by Django 5.0 on 2024-01-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtos_Frasson',
            new_name='Pipe_Produtos',
        ),
    ]
