# Generated by Django 5.0 on 2024-01-05 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_fase_remove_pipe_produtos_phase_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descricao  Pipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pipe',
            },
        ),
        migrations.RenameModel(
            old_name='Pipe_Produtos',
            new_name='Card_Produtos',
        ),
        migrations.AddField(
            model_name='fase',
            name='pipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pipeline.pipe'),
            preserve_default=False,
        ),
    ]
