# Generated by Django 5.0 on 2023-12-18 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipefy_id', models.BigIntegerField(null=True, verbose_name='Id do Usuário no Pipefy')),
                ('job_function', models.CharField(max_length=255, null=True, verbose_name='Cargo ou Função')),
                ('cpf', models.CharField(max_length=255, null=True, verbose_name='CPF')),
                ('bio', models.TextField(default=None, null=True, verbose_name='Biografia')),
                ('birthday', models.DateField(null=True, verbose_name='Data Nascimento')),
                ('contato_celular', models.CharField(max_length=255, null=True, verbose_name='Contato Celular')),
                ('avatar', models.FileField(default='avatars/users/default-avatar.jpg', upload_to='avatars/users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profile',
            },
        ),
    ]
